name: Deploy sicilian image

on:
  push:
    branches:
      - develop
    paths:
      - Dockerfile
jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push sicilian image
        run:  | 
          docker build --build-arg requirements=requirements.txt -t ${{ secrets.ACR_LOGIN_SERVER }}/sicilian:0.0.0
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/sicilian:0.0.0
